Get nearest content POC
enonic/lib-menu pull request #59
Opened 2022-01-18 15:58 UTC by anatol-sialitski

2022-01-18 17:01 UTC, rymsha requested changes

2022-01-18 17:01 UTC, rymsha commented on src/main/java/com/enonic/lib/menu/GetNearestContentHandler.java
> +            return findNearestContent( contentPath.getParentPath() );
If url has many path segments, XP will halt.

2022-01-18 21:34 UTC, anatol-sialitski commented on gradle.properties
> +xpVersion=7.7.0
@alansemenov  Should we upgrade version of the XP?

2022-01-24 09:01 UTC, rymsha requested changes
This PR should be closed

2022-01-24 09:19 UTC, closed without merging